pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'echo "Starting the sourcecode compilation"'
		dir("java") {
                	sh 'echo "Starting the JAVA compilation"'
                	sh 'mvn clean package jxr:jxr surefire-report:report'
		}
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Not implemented yet!"'
            }
        }
        stage('Deploy - Staging') {
            steps {
                sh 'echo "Not implemented yet!"'
            }
        }
        stage('Sanity check') {
            steps {
                input "Does the staging environment look ok?"
            }
        }
        stage('Deploy - Production') {
            steps {
                sh 'echo "Not implemented yet!"'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
	    archiveArtifacts artifacts: 'java/target/*.jar', fingerprint: true
            junit 'java/target/*-reports/*.xml'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
            mail to: 'prl@live.com.pt',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
