pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'echo "Starting the sourcecode compilation"'
		dir("java") {
                	sh 'echo "Starting the JAVA compilation"'
                	sh 'mvn clean package'
		}
            }
        }
    }
}


